### ISSUE TITLE
Video capture

### ISSUE THREAD

**Issue by hajsf** [0xrawsec/golang-win32#3]
How can I use this module to capture photo/video, I read https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-mediacapture but could not understand how to proceed. Thanks

**Comment by qjerome** [comment]
Hi @hajsf,

I am sorry but there are no wrappers for those APIs inside this library.

**Comment by hajsf** [comment]
Thanks for your reply
